# @package _global_

defaults:
  - /dataset@_group_.replica: replica
  - override /model/encoder: noposplat
  - override /model/encoder/backbone: croco
  - override /loss: [mse, lpips]

wandb:
  name: replica_sam
  tags: [replica, 252x252, sam]

model:
  encoder:
    backbone:
      name: vggt_multi
    gaussian_adapter:
      sh_degree: 0
      clamping: -1
    name: vggt
    num_gaussians: 2048
    gs_params_head_type: dpt_gs
    pose_free: true
    intrinsics_embed_loc: None
    intrinsics_embed_type: None
    pretrained_weights: "./pretrained_weights/model.pt"
    init_points: one_point
    gaussian_feature_dim: 256
  decoder:
    make_scale_invariant: true
    decrease_lpf_step: 1000
    feature_detach: false

dataset:
  replica:
    view_sampler:
      warm_up_steps: 37500

optimizer:
  lr: 1e-4
  warm_up_steps: 1000
  backbone_lr_multiplier: 0.01

data_loader:
  train:
    batch_size: 2

train:
  context_view_loss: true
  reproj_model: sam
  feature_rendering_loss: 0.01
  segmentation_loss_weight: 1.0
  sam_model_variant: sam_vit_h
  sam_checkpoint: "./pretrained_weights/sam_vit_h.pth"
  use_lora: false
  lora_rank: 4

trainer:
  max_steps: 5001
  val_check_interval: 1000
  accumulate_grad_batches: 1

checkpointing:
  every_n_train_steps: 10000
  save_top_k: 5
